# Generated by Django 2.2.7 on 2019-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('rut', models.CharField(max_length=25)),
                ('num_cont', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('mensaje', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
